name: Frontend CI (npm)

on:
  push:
    branches: [Eleanor/CI-#154]
  pull_request:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Type check (tsc --noEmit)
        run: npm run type-check

      - name: Lint (eslint .)
        run: npm run lint

      - name: Test (Vitest run)
        run: npm test -- --run

      - name: Build
        run: npm run build