name: Frontend CI

on:
  push:
    branches: [Eleanor/CI-#154]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm exec tsc -p tsconfig.json --noEmit

      - name: Lint (ignore errors)
        run: pnpm run lint || true

      - name: Unit / Component Tests
        run: pnpm test -- --run

      - name: Build
        run: pnpm run build